server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://47.96.80.205;databaseName=HJB_Database
    username: fengzheng
    password: powerSIS#123
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      # 全局默认主键类型
      id-type: auto
      table-underline: true
      logic-not-delete-value: 0
      logic-delete-value: 1
sis:
  ip: 192.0.0.39
  port: 8080
  user: user
  password: user
  path: /rtdb/remoting/RTDBDao-hessian
influx:
  token: lKGD1pDKCUOC_cbek9lYXlf5yK6y59hIGw-6Zx2q8MvgDY9LjlT1_COFKHHgolhsua5Z6Wryki0eOt_0ancWrA==
  url: http://47.96.80.205:8086
  bucket: fengcheng_hist
  org: Jiangsu University of Science and Technology
